### ISSUE TITLE
where is the   sample.lua  ？

### ISSUE THREAD

**Issue by gotope** [robinsloan/torch-rnn-server#1]
th sample.lua -checkpoint cv/checkpoint_10000.t7 -length 2000

the sample.lua not found, and the directory is changed.

**Comment by robinsloan** [comment]
Hi @gotope: I should make an explicit note of this. There is no `sample.lua` in this project, as it's designed to provide generated text through an HTTP server. For convenience, I've included a Ruby script called `sample.rb` that will boot up the server, get a sample, and close it down. Let me know if that works for you.

**Comment by gotope** [comment]
Hello @robinsloan,   the sample.rb will automatically sample when start server？

**Comment by robinsloan** [comment]
Hi @gotope: no, they're two different things. You can either:
1. Run `th server.lua` to start the server, which can be accessed via an HTTP request (see the example in README); or
2. Run `ruby sample.rb "here is some start text"` to sample text directly on the command line.

**Comment by gotope** [comment]
@robinsloan
1. yes, that is what I run rnn-writer had done.
2. ruby sample.rb,  just for the command line sample text directly on-the-fly？
thanks

**Comment by robinsloan** [comment]
@gotope, yep! You do have to specify some text to get the model started -- so `ruby sample.rb "foo bar"` would work. Don't hesitate to open `sample.rb` and edit the code to do what you want!

**Comment by gotope** [comment]
@robinsloan  
BTW,    To process train other language (Dword format)， should I modify the language.lua script？

**Comment by robinsloan** [comment]
@gotope, as long as it's Unicode text, you should be fine! Although I should say: `torch-rnn-server` makes several assumptions about how sentences are terminated. It's designed for a very specific purpose -- interfacing with [`rnn-writer`](https://github.com/robinsloan/torch-rnn-server). So, it probably makes sense to get your model up and running in regular [`torch-rnn`](https://github.com/jcjohnson/torch-rnn) and only then porting it over to this project if you need the HTTP serving capability.

**Comment by gotope** [comment]
@robinsloan ,  ok,  thanks.
