### ISSUE TITLE
Download pretrained model returns 404

### ISSUE THREAD

**Issue by zj88** [robinsloan/torch-rnn-server#11]
Trying wget http://from.robinsloan.com/rnn-writer/scifi-model.zip redirects me to https://dl.dropboxusercontent.com/u/156973/from.robinsloan.com/rnn-writer/scifi-model.zip which then responds with 404 Not Found. Tried also in browser with the same result. Would be grateful for some help

**Comment by robinsloan** [comment]
Ah, rats. That's Dropbox finally turning off their Public folder functionality.

Just fixed it. Thanks for the heads up.
