### ISSUE TITLE
docker with all dependencies?

### ISSUE THREAD

**Issue by anaderi** [robinsloan/torch-rnn-server#5]
Is this project alive? Maybe to simplify installation for end-users you could create docker image with all required stuff?

**Comment by anaderi** [comment]
I see there is Dockerfile, but why don't you upload the created image to https://hub.docker.com/r/robinsloan/ ?

**Comment by robinsloan** [comment]
Hi @anaderi: yes, it's alive! No new features being added, but it's being used by me and others regularly.

I didn't make the Dockerfile myself; it was contributed by someone else. I've never used Docker personally. Have you run across any clear tutorials that describe how to set up a Docker image with cross-platform access to the GPU?
