### ISSUE TITLE
what happened to the requirements.txt file?

### ISSUE THREAD

**Issue by 7hacker** [robinsloan/torch-rnn-server#8]
Hi, Im trying to set up this fantastic server but I found its missing the requirements.txt file that is in the original torch-rnn repo. Is the correct way to get started, by using the requirements.txt file from that repo?

**Comment by robinsloan** [comment]
Hi there! Good question… the answer is probably yes. (I'm not a Python expert, so you'll have to indulge me: what's the purpose of `requirements.txt`?)

**Comment by 7hacker** [comment]
The requirements.txt file is a necessary part of the step titled "Python setup" of the README. 

requirements.txt contains all of the dependencies such as cython, numpy etc that are necessary in training a new model. My guess is that since torch-rnn-server is to be used with pretrained model, it has been excluded from this repo?

**Comment by robinsloan** [comment]
Ah… that's a good catch. I didn't use that method to install the dependencies. I can add the file myself at some point -- but if you want to submit a pull request adding it back, I'll accept it gladly! Thanks.

**Comment by 7hacker** [comment]
Done, sent you a PR! Thanks!
